### ISSUE TITLE
[Bug] Compatibility with Drag Ruler (for familiar riding)

### ISSUE THREAD

**Issue by cadowtin** [Saibot393/Rideable#8]
With bot this and drag ruler enabled, the mounted doesn't move and i get the following error
```
foundry.js:753 TypeError: Error thrown in hooked function '' for hook 'updateToken'. Cannot read properties of undefined (reading 'w')
[Detected 2 packages: Rideable, drag-ruler]
    at Ridingmanager.planRiderTokens (RidingScript.js:175:56)
    at Ridingmanager.OnTokenupdate (RidingScript.js:40:20)
    at Object.fn (RidingScript.js:309:52)
    at #call (foundry.js:730:20)
    at Hooks.callAll (foundry.js:687:17)
    at ClientDatabaseBackend.callback (foundry.js:13709:13)
    at foundry.js:13682:43
    at Array.map (<anonymous>)
    at #handleUpdateDocuments (foundry.js:13682:33)
    at async TokenDocumentPF2e.updateDocuments (commons.js:7902:23)
    at async DragRulerRuler.animateEntities (foundry_imports.js:94:3)
    at async DragRulerRuler.moveEntities (foundry_imports.js:47:2)
```

**Comment by Saibot393** [comment]
Thank you for the bug report. The bug should now be fixed with the new v1.5.1.
